# Generated by Django 4.2 on 2023-05-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_banner_img'),
    ]

    operations = [
        migrations.DeleteModel('Occasion'),
    ]
