# Generated by Django 4.2 on 2023-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_occasion_model'),
    ]

    operations = [
        migrations.RenameModel('Brand', 'Occasion'),
    ]
